import type { Shop } from "@/lib/types";

export const shops: Shop[] = [
  {
    id: "city-bazaar",
    name: "City Bazaar Convenience",
    ownerName: "Ravi Kumar",
    ownerEmail: "owner@airloo.in",
    category: "Shop",
    address: "12 Market Road, near Central Bus Stand",
    locality: "City Bazaar",
    city: "Coimbatore",
    latitude: 11.0168,
    longitude: 76.9558,
    distanceKm: 0.7,
    status: "needs-cleaning",
    rating: 4.2,
    facilities: ["Public toilet", "Handwash", "Women friendly"],
    sensors: [
      {
        deviceId: "toilet_1",
        doorState: "OPEN",
        openCount: 247,
        closeCount: 245,
        sessionsToday: 42,
        temperatureC: 29.4,
        humidityPct: 71,
        pressureHpa: 1008,
        gasResistanceKohms: 82,
        airQualityIndex: 164,
        lastEventAt: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
      },
    ],
  },
  {
    id: "metro-snacks",
    name: "Metro Snacks Point",
    ownerName: "Nisha Varghese",
    ownerEmail: "nisha@airloo.in",
    category: "Cafe",
    address: "Platform Road, opposite Metro Gate 2",
    locality: "Railway Colony",
    city: "Coimbatore",
    latitude: 11.0012,
    longitude: 76.9674,
    distanceKm: 1.4,
    status: "healthy",
    rating: 4.6,
    facilities: ["Public toilet", "Accessible entry", "Drinking water"],
    sensors: [
      {
        deviceId: "toilet_2",
        doorState: "CLOSED",
        openCount: 118,
        closeCount: 118,
        sessionsToday: 18,
        temperatureC: 28.1,
        humidityPct: 63,
        pressureHpa: 1009,
        gasResistanceKohms: 142,
        airQualityIndex: 74,
        lastEventAt: new Date(Date.now() - 1000 * 60 * 21).toISOString(),
      },
    ],
  },
  {
    id: "lake-view-medicals",
    name: "Lake View Medicals",
    ownerName: "Farhan Ali",
    ownerEmail: "farhan@airloo.in",
    category: "Medical store",
    address: "4 Lake View Street, RS Puram",
    locality: "RS Puram",
    city: "Coimbatore",
    latitude: 11.009,
    longitude: 76.9501,
    distanceKm: 2.2,
    status: "offline",
    rating: 4.0,
    facilities: ["Public toilet", "Baby care shelf"],
    sensors: [
      {
        deviceId: "toilet_3",
        doorState: "CLOSED",
        openCount: 52,
        closeCount: 52,
        sessionsToday: 0,
        lastEventAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      },
    ],
  },
];

export function getShop(shopId: string) {
  return shops.find((shop) => shop.id === shopId);
}
